### ISSUE TITLE
[Bug]: Log in needs to be done twice

### ISSUE THREAD

**Issue by albertocottica** [UNDP-Accelerator-Labs/platform#114]
### Issue description

When logging in, login credentials need to be entered twice for login to take effect. There is no error message.

### Where did this happen?

In the login page

### What do you expect?

For login to take immediate effect. 

### Platform

All Platforms

### What browsers are you seeing the problem on?

Firefox

### Add any other relevant details

Relevant info

**Comment by this-pama** [comment]
Fixed with #57
