### ISSUE TITLE
[ENHANCEMENT]: ensure consistency of the search syntax

### ISSUE THREAD

**Issue by albertocottica** [UNDP-Accelerator-Labs/platform#116]
### What areas do you propose needs enhancement or improvement?

Search is inconsistent across platforms. I have not found documentation of the syntax, so I'm left guessing. Are boolean operators supported? REGEX? 

### Where is the current state/behavior?

* In the blogs platform, a search for `"food security"` returns nothing, so presumably only occurrences that contain the whole string, including the quote signs.
* In the ALP platform, a search for `"food security"` returns occurrences of the string `food security`, *without* the quote signs. 
* In the blogs platform, a search for `food security` returns occurrences of the string `food security`.

### How will the proposed enhancement improve the system?

Guessing is time consuming.

### Add why this is beneficial.

Faster and less frustrating.

**Comment by myjyby** [comment]
Thanks @albertocottica. Yes we are aware the search function is different for the blogs. @thisdapo and I went over this these last couple of days. Please expect a major update (which will include a consistent search function with the other platforms) in the next few days.
