### ISSUE TITLE
[Bug]: Some blog posts from South Africa show up as "unknown country"

### ISSUE THREAD

**Issue by albertocottica** [UNDP-Accelerator-Labs/platform#127]
### Issue description

![image](https://github.com/UNDP-Accelerator-Labs/platform/assets/1976806/ef9aebcb-af4f-4251-ae44-e26f04e6047e)

Resolves to https://www.undp.org/south-africa/blog/sinking-seaweed-japan-sdgs-innovation-challenge

On the other hand, from the same search this one is correctly shown as "South Africa": https://www.undp.org/south-africa/blog/welcome-water-island-%E2%80%93-where-innovation-roams-free

### Where did this happen?

Obtained from this search: https://acclabs.azurewebsites.net/en/browse/blog/preview?source=blog&search=aquaculture

### What do you expect?

What do you expect? 

### Platform

All Platforms Except Global

### What browsers are you seeing the problem on?

Firefox

### Add any other relevant details

Relevant info

**Comment by this-pama** [comment]
Closing this as blog search via the global platform is now obsolete. Use the insight hub when searching for blogs or semantic search across all platforms.
https://insights.sdg-innovation-commons.org/browse
