### ISSUE TITLE
[Bug]: language param disappears from path

### ISSUE THREAD

**Issue by myjyby** [UNDP-Accelerator-Labs/platform#135]
### Issue description

every so often, the language param (second param in the url path) disappears which then breaks all navigation. This is likely due to the url rewriting with Google translate.

### Where did this happen?

on all platforms.

### What do you expect?

that the language param remains.

### Platform

All Platforms

### What browsers are you seeing the problem on?

Chrome

### Add any other relevant details

@thisdapo can you please look into this?

**Comment by this-pama** [comment]
Any idea how to reproduce this?

In the meantime, I have defaulted the page language to `en` in the URL rewrite function in #130 . I guess this is caused when language is NULL. How to reproduce this will be helpful to debug.
```
function rewriteUrl(lang = 'en', reload = false){
		const currentUrl = new URL(window.location);
		const languagePattern = /^\/[a-z]{2,3}\//;
		const newPath = currentUrl.pathname.replace(languagePattern, "/" + lang + "/");
		currentUrl.pathname = newPath;
		const newUrl = `${currentUrl}`;

		if(reload) window.location.href = newUrl;
		else window.history.replaceState({}, "", newUrl);
	}
```

**Comment by this-pama** [comment]
This is fixed. Closing this.
