### ISSUE TITLE
[Issue]: Internal Server Error when creating a new contributor

### ISSUE THREAD

**Issue by egustale** [UNDP-Accelerator-Labs/platform#142]
### Contact Details

eduardo.gustale@undp.org

### Issue description

After trying to create and save a new contributor in the Action Plan platform an internal server error appeared.
It allowed me to save, but it showed an error after clicking the save button.

### Steps to reproduce.

New- Contributor - Fill all fields - click Save

### Where did this happen?

Action Plan Platform under creating a new contributor

### Platform

Action Plan

### What browsers are you seeing the problem on?

Chrome

### Add any other relevant details

I need to create a new user for the Independent Evaluation Office

**Comment by JosuaKrause** [comment]
this should be fixed now
