### ISSUE TITLE
[Bug]: Upload Consent form option not working

### ISSUE THREAD

**Issue by acclabmx** [UNDP-Accelerator-Labs/platform#207]
### Contact Details

jorge.munguia@undp.org

### Issue description

When trying to add a consent form to a new solution pad, the option to link a file seems broken, and no file linking is possible.

![Captura de pantalla 2023-12-07 a la(s) 3 57 36 p m](https://github.com/UNDP-Accelerator-Labs/platform/assets/75092570/7bae1355-24aa-44aa-b9e8-c0b69a458fe7)

### Where did this happen?

[url](https://consent.sdg-innovation-commons.org/en/contribute/resource?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1dWlkIjoiYTE4MDU1MDMtYjM0MC00ZTc3LThjNGEtNDlmNGRlZWQ0OTBmIiwiY2FsbGJhY2siOnsicGFkX2lkIjoiNjUzNiIsImVsZW1lbnRfaWQiOiI5ZGVkMDFjNi01YTVlLTQyZWQtYjBiYy03M2E4ODk5MzJhZjUiLCJuYW1lIjoiY29uc2VudCIsInR5cGUiOiJhdHRhY2htZW50IiwiaG9zdCI6InNvbHV0aW9ucy5zZGctaW5ub3ZhdGlvbi1jb21tb25zLm9yZyIsImVuZHBvaW50IjoiL3NhdmUvcmVzb3VyY2UiLCJyZWZlcmVyIjoiaHR0cHM6Ly9zb2x1dGlvbnMuc2RnLWlubm92YXRpb24tY29tbW9ucy5vcmcvZW4vZWRpdC9wYWQ_aWQ9NjUzNiIsInV1aWQiOiJhMTgwNTUwMy1iMzQwLTRlNzctOGM0YS00OWY0ZGVlZDQ5MGYifSwiaWF0IjoxNzAxOTg1OTE3LCJleHAiOjE3MDE5ODY4MTd9.bwHXMQY71X_ObinD_RcV_PVRtS2Cj3Q-vMplWH4zVG0) 

### What do you expect?

I expect that an option to upload a file is available.

### Platform

Solution Mapping

### What browsers are you seeing the problem on?

Firefox

### Add any other relevant details

Relevant info: A template of a consent form to download should be available to streamline the process. Would a consent form be possible directly on the platform (i.e. a form with a signing feature directly on the website)?

**Comment by myjyby** [comment]
This is fixed in #203.
