### ISSUE TITLE
"Relevant" buttons no longer work in Firefox

### ISSUE THREAD

**Issue by albertocottica** [UNDP-Accelerator-Labs/platform#230]
Based on [this](https://learningplans.sdg-innovation-commons.org/en/browse/pads/published?page=1&search=&sdgs=334&sdgs=351&sdgs=368&sdgs=385&sdgs=402&sdgs=317&explorationid=67). 

Clicking on the "Relevant" or "Unrelated" buttons has no effect, though I am in the context of an exploration (selected correctly in the drop-down menu of the explorations).

![Image](https://github.com/UNDP-Accelerator-Labs/platform/assets/1976806/467db4da-80d0-4268-9a4c-46dc60a58d5f)

**Comment by JosuaKrause** [comment]
@albertocottica changes are live. it should work now
