### ISSUE TITLE
[Bug]: Cannot revoke users 

### ISSUE THREAD

**Issue by myjyby** [UNDP-Accelerator-Labs/platform#248]
### Issue description

Trying to revoke a user who has left the network on the login platform. I get redirected to the login page, and the user is not revoked.

### Where did this happen?

https://login.sdg-innovation-commons.org/

### What do you expect?

The user should be revoked (meaning their user rights should be downgraded to 0) and I should not be redirected to login

### Platform

All Platforms

### Add any other relevant details

You might want to add the login platform to the platform list above

**Comment by this-pama** [comment]
Fixed
