### ISSUE TITLE
Pads cannot be removed from collections

### ISSUE THREAD

**Issue by albertocottica** [UNDP-Accelerator-Labs/platform#53]
When visualizing a collection, pads are shown with a "x" icon, normally intended to remove that pad from that collection. That functionality does not work.

**Comment by myjyby** [comment]
Hi @albertocottica. This is another one of those issues that I cannot reproduce. It works fine on all modern browsers on my end. Can you please detail what happens on your end?

**Comment by albertocottica** [comment]
This seems to have been fixed!
