### ISSUE TITLE
Password reset does not work

### ISSUE THREAD

**Issue by albertocottica** [UNDP-Accelerator-Labs/platform#54]
Clicking on the "Reset password" link results in a message that a reset link has been sent. However, I received none. 

![Image](https://github.com/UNDP-Accelerator-Labs/platform/assets/1976806/7ee360bb-d68b-468b-80f2-b462b6742464)

**Comment by thisdapo** [comment]
@albertocottica did you check your spam folder? Sometimes, the email hits the spam folder.

**Comment by myjyby** [comment]
I just tried again and it worked for me.

**Comment by albertocottica** [comment]
> @albertocottica did you check your spam folder? Sometimes, the email hits the spam folder.

Indeed, found it. Apologies.
