### ISSUE TITLE
change "Review" to "My Review"

### ISSUE THREAD

**Issue by JosuaKrause** [UNDP-Accelerator-Labs/platform#69]
as suggested by @egustale on the left side it would be more clear to write "My Reviews"

<img width="244" alt="Screenshot 2023-07-18 at 2 36 18 PM" src="https://github.com/UNDP-Accelerator-Labs/platform/assets/533142/86f85404-c7c1-499d-8cf7-4189bf3a3ff5">

**Comment by this-pama** [comment]
Fixed in PR #74
