### ISSUE TITLE
Review process stuck when an experiment has been sent back for further review/ rejected - Experimenters Platform

### ISSUE THREAD

**Issue by egustale** [UNDP-Accelerator-Labs/platform#71]
When a preprint experiment is sent to review and gets rejected the author has no way of editing the experiment or send it back for review. If the experiment gets "retracted" it can re submit for review but reviewers are unable to re approve.

*Joshua and I manually published id=424 which had this situation.

**Comment by JosuaKrause** [comment]
I only changed the pad status of 424. Whatever is causing the issue in the reviews is still there

**Comment by JosuaKrause** [comment]
reviews are: https://acclabs-experiments.azurewebsites.net/en/view/pad?id=433 and https://acclabs-experiments.azurewebsites.net/en/edit/pad?id=441

**Comment by JosuaKrause** [comment]
@egustale let us know if this issue is resolved now

**Comment by JosuaKrause** [comment]
issue is resolved but flow needs improvements
