### ISSUE TITLE
Comments and review questions cannot be seen by reviewers or author - Experimenters Platform

### ISSUE THREAD

**Issue by egustale** [UNDP-Accelerator-Labs/platform#72]
When an experiment review is finished, authors are only able to see if the experiment got accepted or rejected. If rejected they are unable to see the comments left by the reviewer. Additionally once any changes are made it was impossible to find out how to send it again for review.

**Comment by JosuaKrause** [comment]
https://acclabs-experiments.azurewebsites.net/en/edit/pad?id=424 was an example of this

**Comment by JosuaKrause** [comment]
reviews are: https://acclabs-experiments.azurewebsites.net/en/view/pad?id=433 and https://acclabs-experiments.azurewebsites.net/en/edit/pad?id=441

**Comment by myjyby** [comment]
This should be resolved now.
