### ISSUE TITLE
[ENHANCEMENT]: What is the best way to clear the filter?

### ISSUE THREAD

**Issue by albertocottica** [UNDP-Accelerator-Labs/platform#90]
### What areas do you propose needs enhancement or improvement?

it would be great to have a way to compose the query by turning on and off different filters. For example, I filtered in Argentina and I want to add Brazil, but I no longer even see Brazil in the "countries" filter unless I backpedal to the previous page. 

### Where is the current state/behavior?

Right now, the filter by country works like this: 

1. I choose a country press enter
2. Now I can only see the pads of that country. 
3. To clear the filter, I currently hit the "Back" button of the browser (slow) or even manually edit the query in the URL (cumbersome and need to get the URL exactly right, including the escaped characters). 

### How will the proposed enhancement improve the system?

It allows for faster and less frustrating refinement of the queries.

**Comment by JosuaKrause** [comment]
opened a dedicated bug ticket #96

**Comment by myjyby** [comment]
fixed in #104
