### ISSUE TITLE
[Bug]: Country filter list only shows selected countries

### ISSUE THREAD

**Issue by JosuaKrause** [UNDP-Accelerator-Labs/platform#96]
### Issue description

The filter country list allows for multiple countries to be selected. Once the page reloads when issuing the query the country list only shows the selected countries. This is not necessary as the list already supports highlighting the selected countries. Additionally, it makes it impossible to change the selection of countries in a meaningful way.

### Where did this happen?

filter module

### What do you expect?

The country list should be unchanged and the selected countries should be highlighted. It would be nice to bring the selected countries to the top of the list but it is not strictly required.

### Platform

All Platforms

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

**Comment by myjyby** [comment]
related #90 and resolved in #104
