### ISSUE TITLE
[Bug]: filters don't show if the search result is empty

### ISSUE THREAD

**Issue by JosuaKrause** [UNDP-Accelerator-Labs/platform#98]
### Issue description

if searching something and the result set is empty the filter component doesn't show up.
you can end up in a situation where you select filters, search without results, and are unable to remove filters afterwards because the module doesn't show up

### Where did this happen?

-

### What do you expect?

-

### Platform

All Platforms

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### Add any other relevant details

-

**Comment by JosuaKrause** [comment]
see also #90

**Comment by myjyby** [comment]
related to #90 and solved in #104
